### ISSUE TITLE
Error loading cities.csv in chapter 4

### ISSUE THREAD

**Issue by markhorgan** [PacktPublishing/Learning-D3js-5-Mapping-Second-Edition#1]
In example-6.html (line 67) and example-7.html (line 64) in Chapter04

`d3.csv('cities.csv', function(cities) {`

should be:

`d3.csv('cities.csv').then(function(cities) {`

Cities don't show up otherwise.

**Comment by gaurav-packt** [comment]
Thanks for the update. It will surely assist the readers to resolve the issue.
